### ISSUE TITLE
Can't save store to other stores, only to default

### ISSUE THREAD

**Issue by ps202** [ClaudiuCreanga/magento2-store-locator-stockists-extension#4] opened 2016-11-19 06:52 UTC
As stated above, I can't save store to other stores, only to default.
It does not matter which store view I am selecting before saving the store, it will always be changed to the default sites default store.

**Comment by ClaudiuCreanga** [comment] 2016-11-19 20:13
This bug should be fixed in the latest version of the extension. Please check v. 1.0.16

**Comment by genfish** [comment] 2017-03-16 09:22
hi, i reproduced this bug in magento 2.1.2. forever it's saved the default store. and, other question: it's not permitted save a stockist in multiple stores?

**Comment by ClaudiuCreanga** [comment] 2017-03-16 09:39
HI,

you should check the last commit https://github.com/ClaudiuCreanga/magento2-store-locator-stockists-extension/commit/46425fb6dc842ca311e36718f7c68a1697986006 and save it manually in that file.

**Comment by genfish** [comment] 2017-03-16 11:50
thanks for your fast answer! now it's saved correctly one store, but not multiple stores. i think this is because the field in database table is smallint and can't save string value, for example: stores "1,2".

**Comment by ClaudiuCreanga** [comment] 2017-03-16 11:56
Thanks. I'll have a look. didn't try with multiple stores.

**Comment by ClaudiuCreanga** [comment] 2017-03-16 23:39
You were right. I made the change in code. You'll have to make the change manually in the database. Thanks!

**Comment by genfish** [comment] 2017-03-17 10:01
Works perfect! Good job. Only one minor issue: in the stockists list doesn't see the stores selected (in the admin).

**Comment by ClaudiuCreanga** [comment] 2017-04-03 16:23
This has been fixed in 2.0

**Closed by ClaudiuCreanga** 2017-04-03 16:23 UTC
